import { createClient } from '@supabase/supabase-js';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import './style.css';

const url=import.meta.env.VITE_SUPABASE_URL||'';
const key=import.meta.env.VITE_SUPABASE_ANON_KEY||'';
const supabase=(url&&key)?createClient(url,key):null;
let state={active:false,watch:null,last:null,km:0,start:null,timer:null,points:[],map:null,line:null,marker:null,shiftId:null,user:null};
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const $=s=>document.querySelector(s);
const dist=(a,b)=>{const R=6371,rad=x=>x*Math.PI/180,dLat=rad(b.lat-a.lat),dLon=rad(b.lon-a.lon),q=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q));};
const fmt=ms=>{let s=Math.floor(ms/1000),h=Math.floor(s/3600);s%=3600;let m=Math.floor(s/60);s%=60;return [h,m,s].map(x=>String(x).padStart(2,'0')).join(':')};
function render(){const inc=+$('[name=income]').value||0,fuel=+$('[name=fuel]').value||0,other=+$('[name=other]').value||0,p=inc-fuel-other;$('#km').textContent=state.km.toFixed(2).replace('.',',')+' km';$('#income').textContent=money(inc);$('#expense').textContent=money(fuel+other);$('#profit').textContent=money(p);$('#profitKm').textContent=money(state.km?p/state.km:0);if(state.start)$('#timer').textContent=fmt(Date.now()-state.start);}
function drawMap(){if(!state.map)return;if(state.points.length){const ll=state.points.map(p=>[p.lat,p.lon]);if(!state.line)state.line=L.polyline(ll).addTo(state.map);else state.line.setLatLngs(ll);const last=ll.at(-1);if(!state.marker)state.marker=L.marker(last).addTo(state.map);else state.marker.setLatLng(last);state.map.setView(last,15);}}
async function startTurn(){if(!navigator.geolocation)return alert('GPS não disponível neste navegador.');state.active=true;state.start=Date.now();state.km=0;state.last=null;state.points=[];$('#toggle').textContent='■ Encerrar turno';$('#status').textContent='● Turno em andamento';$('#status').className='pill online';$('#gps').textContent='GPS ativo';if(supabase&&state.user){const {data,error}=await supabase.from('shifts').insert({user_id:state.user.id,started_at:new Date().toISOString(),status:'active'}).select().single();if(!error)state.shiftId=data.id;}state.watch=navigator.geolocation.watchPosition(async pos=>{const p={lat:pos.coords.latitude,lon:pos.coords.longitude,accuracy:pos.coords.accuracy};if(state.last){const d=dist(state.last,p);if(d>=0.005&&d<0.5)state.km+=d;}state.last=p;state.points.push(p);drawMap();render();if(supabase&&state.shiftId){await supabase.from('gps_points').insert({shift_id:state.shiftId,user_id:state.user.id,latitude:p.lat,longitude:p.lon,accuracy:p.accuracy});}},e=>$('#gps').textContent='GPS: '+e.message,{enableHighAccuracy:true,maximumAge:5000,timeout:15000});state.timer=setInterval(render,1000);}
async function stopTurn(){state.active=false;if(state.watch!==null)navigator.geolocation.clearWatch(state.watch);clearInterval(state.timer);if(supabase&&state.shiftId){await supabase.from('shifts').update({ended_at:new Date().toISOString(),distance_km:state.km,status:'finished',income:+$('[name=income]').value||0,fuel_cost:+$('[name=fuel]').value||0,other_expenses:+$('[name=other]').value||0}).eq('id',state.shiftId);}state.watch=null;state.shiftId=null;$('#toggle').textContent='▶ Iniciar turno';$('#status').textContent='● Turno encerrado';$('#status').className='pill offline';$('#gps').textContent='GPS encerrado';render();}
function authBox(){return `<div class="auth"><input id="email" type="email" placeholder="Seu e-mail"><input id="pass" type="password" placeholder="Senha"><button id="login">Entrar</button><button id="signup" class="secondary">Criar conta</button><small>${supabase?'Supabase conectado via variáveis de ambiente.':'Modo demonstração: configure VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY.'}</small></div>`}
function app(){document.querySelector('#app').innerHTML=`<div class="app"><header><div><span class="eyebrow">DRIVERPRO</span><h1>Controle seu turno</h1><p>GPS + financeiro em um só lugar.</p></div><div id="status" class="pill offline">● Turno parado</div></header><section class="card authcard" id="auth">${authBox()}</section><main><section class="hero card"><div><span class="label">KM DO TURNO</span><strong id="km">0,00 km</strong><small id="timer">00:00:00</small></div><button id="toggle" class="primary">▶ Iniciar turno</button></section><section class="grid"><article class="card metric"><span>Faturamento</span><b id="income">R$ 0,00</b></article><article class="card metric"><span>Despesas</span><b id="expense">R$ 0,00</b></article><article class="card metric"><span>Lucro</span><b id="profit">R$ 0,00</b></article><article class="card metric"><span>Lucro / km</span><b id="profitKm">R$ 0,00</b></article></section><section class="card"><h2>Resumo financeiro</h2><div class="formgrid"><label>Faturamento<input name="income" type="number" step="0.01" placeholder="0,00"></label><label>Gasolina<input name="fuel" type="number" step="0.01" placeholder="0,00"></label><label>Outras despesas<input name="other" type="number" step="0.01" placeholder="0,00"></label><label>Meta<input name="goal" type="number" step="0.01" value="400"></label></div></section><section class="card mapcard"><div class="section-head"><h2>Trajeto GPS</h2><span id="gps">Aguardando GPS</span></div><div id="map"></div></section></main><footer>DriverPro • Dados financeiros e GPS sincronizados no Supabase quando configurado.</footer></div>`;state.map=L.map('map').setView([-28.6,-49.3],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(state.map);$('#toggle').onclick=()=>state.active?stopTurn():startTurn();document.querySelectorAll('input').forEach(x=>x.oninput=render);$('#login').onclick=login;$('#signup').onclick=signup;}
async function login(){if(!supabase)return alert('Configure o Supabase na Vercel/.env.local primeiro.');const {data,error}=await supabase.auth.signInWithPassword({email:$('#email').value,password:$('#pass').value});if(error)return alert(error.message);state.user=data.user;$('#auth').innerHTML=`<b>Conectado:</b> ${state.user.email}`;}
async function signup(){if(!supabase)return alert('Configure o Supabase primeiro.');const {error}=await supabase.auth.signUp({email:$('#email').value,password:$('#pass').value});alert(error?error.message:'Conta criada. Verifique seu e-mail se a confirmação estiver habilitada.');}
app();render();
