create extension if not exists pgcrypto;
create table if not exists public.shifts (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
 started_at timestamptz not null default now(), ended_at timestamptz, status text not null default 'active',
 distance_km numeric(12,3) not null default 0, income numeric(12,2) not null default 0,
 fuel_cost numeric(12,2) not null default 0, other_expenses numeric(12,2) not null default 0,
 created_at timestamptz not null default now()
);
create table if not exists public.gps_points (
 id bigint generated by default as identity primary key, shift_id uuid not null references public.shifts(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade, latitude double precision not null,
 longitude double precision not null, accuracy double precision, recorded_at timestamptz not null default now()
);
alter table public.shifts enable row level security; alter table public.gps_points enable row level security;
drop policy if exists shifts_owner on public.shifts; create policy shifts_owner on public.shifts for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists gps_owner on public.gps_points; create policy gps_owner on public.gps_points for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create index if not exists gps_points_shift_idx on public.gps_points(shift_id,recorded_at);
